[2025-02-22 11:18:16,005] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: lead_scoring_data_pipeline.map_city_tier scheduled__2024-06-16T00:00:00+00:00 [queued]>
[2025-02-22 11:18:16,010] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: lead_scoring_data_pipeline.map_city_tier scheduled__2024-06-16T00:00:00+00:00 [queued]>
[2025-02-22 11:18:16,010] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2025-02-22 11:18:16,010] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2025-02-22 11:18:16,010] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2025-02-22 11:18:16,030] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): map_city_tier> on 2024-06-16 00:00:00+00:00
[2025-02-22 11:18:16,034] {standard_task_runner.py:52} INFO - Started process 59361 to run task
[2025-02-22 11:18:16,036] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'lead_scoring_data_pipeline', 'map_city_tier', 'scheduled__2024-06-16T00:00:00+00:00', '--job-id', '492', '--raw', '--subdir', 'DAGS_FOLDER/lead_scoring_data_pipeline.py', '--cfg-path', '/tmp/tmpnwh7dbqm', '--error-file', '/tmp/tmp_ba_uf4i']
[2025-02-22 11:18:16,037] {standard_task_runner.py:80} INFO - Job 492: Subtask map_city_tier
[2025-02-22 11:18:16,095] {task_command.py:371} INFO - Running <TaskInstance: lead_scoring_data_pipeline.map_city_tier scheduled__2024-06-16T00:00:00+00:00 [running]> on host 3766485c0f6d
[2025-02-22 11:18:16,176] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=lead_scoring_data_pipeline
AIRFLOW_CTX_TASK_ID=map_city_tier
AIRFLOW_CTX_EXECUTION_DATE=2024-06-16T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-06-16T00:00:00+00:00
[2025-02-22 11:18:16,177] {logging_mixin.py:115} INFO - Using Database: /workspace/Assignment/01_data_pipeline/scripts/utils_output.db
[2025-02-22 11:18:16,177] {logging_mixin.py:115} INFO - Error in mapping city tiers: unable to open database file
[2025-02-22 11:18:16,177] {python.py:173} INFO - Done. Returned value was: None
[2025-02-22 11:18:16,182] {taskinstance.py:1415} INFO - Marking task as SUCCESS. dag_id=lead_scoring_data_pipeline, task_id=map_city_tier, execution_date=20240616T000000, start_date=20250222T111816, end_date=20250222T111816
[2025-02-22 11:18:16,208] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-02-22 11:18:16,252] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
