[2025-02-22 11:01:21,931] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: lead_scoring_data_pipeline.map_city_tier manual__2025-02-22T11:00:34+00:00 [queued]>
[2025-02-22 11:01:21,937] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: lead_scoring_data_pipeline.map_city_tier manual__2025-02-22T11:00:34+00:00 [queued]>
[2025-02-22 11:01:21,937] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2025-02-22 11:01:21,937] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2025-02-22 11:01:21,937] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2025-02-22 11:01:22,056] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): map_city_tier> on 2025-02-22 11:00:34+00:00
[2025-02-22 11:01:22,064] {standard_task_runner.py:52} INFO - Started process 49170 to run task
[2025-02-22 11:01:22,067] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'lead_scoring_data_pipeline', 'map_city_tier', 'manual__2025-02-22T11:00:34+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/lead_scoring_data_pipeline.py', '--cfg-path', '/tmp/tmpvs4n0g56', '--error-file', '/tmp/tmpsylzr90k']
[2025-02-22 11:01:22,068] {standard_task_runner.py:80} INFO - Job 30: Subtask map_city_tier
[2025-02-22 11:01:22,214] {task_command.py:371} INFO - Running <TaskInstance: lead_scoring_data_pipeline.map_city_tier manual__2025-02-22T11:00:34+00:00 [running]> on host 3766485c0f6d
[2025-02-22 11:01:22,503] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=lead_scoring_data_pipeline
AIRFLOW_CTX_TASK_ID=map_city_tier
AIRFLOW_CTX_EXECUTION_DATE=2025-02-22T11:00:34+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-02-22T11:00:34+00:00
[2025-02-22 11:01:22,505] {logging_mixin.py:115} INFO - Using Database: /workspace/Assignment/01_data_pipeline/scripts/utils_output.db
[2025-02-22 11:01:22,505] {logging_mixin.py:115} INFO - Error in mapping city tiers: unable to open database file
[2025-02-22 11:01:22,505] {python.py:173} INFO - Done. Returned value was: None
[2025-02-22 11:01:22,521] {taskinstance.py:1415} INFO - Marking task as SUCCESS. dag_id=lead_scoring_data_pipeline, task_id=map_city_tier, execution_date=20250222T110034, start_date=20250222T110121, end_date=20250222T110122
[2025-02-22 11:01:22,681] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-02-22 11:01:22,821] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
