[2025-02-22 11:33:20,226] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: lead_scoring_data_pipeline.map_city_tier scheduled__2024-10-06T00:00:00+00:00 [queued]>
[2025-02-22 11:33:20,231] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: lead_scoring_data_pipeline.map_city_tier scheduled__2024-10-06T00:00:00+00:00 [queued]>
[2025-02-22 11:33:20,231] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2025-02-22 11:33:20,231] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2025-02-22 11:33:20,231] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2025-02-22 11:33:20,249] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): map_city_tier> on 2024-10-06 00:00:00+00:00
[2025-02-22 11:33:20,253] {standard_task_runner.py:52} INFO - Started process 68951 to run task
[2025-02-22 11:33:20,255] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'lead_scoring_data_pipeline', 'map_city_tier', 'scheduled__2024-10-06T00:00:00+00:00', '--job-id', '940', '--raw', '--subdir', 'DAGS_FOLDER/lead_scoring_data_pipeline.py', '--cfg-path', '/tmp/tmppm0qm4vw', '--error-file', '/tmp/tmpuidohdif']
[2025-02-22 11:33:20,256] {standard_task_runner.py:80} INFO - Job 940: Subtask map_city_tier
[2025-02-22 11:33:20,296] {task_command.py:371} INFO - Running <TaskInstance: lead_scoring_data_pipeline.map_city_tier scheduled__2024-10-06T00:00:00+00:00 [running]> on host 3766485c0f6d
[2025-02-22 11:33:20,367] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=lead_scoring_data_pipeline
AIRFLOW_CTX_TASK_ID=map_city_tier
AIRFLOW_CTX_EXECUTION_DATE=2024-10-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-10-06T00:00:00+00:00
[2025-02-22 11:33:20,368] {logging_mixin.py:115} INFO - Using Database: /workspace/Assignment/01_data_pipeline/scripts/utils_output.db
[2025-02-22 11:33:20,368] {logging_mixin.py:115} INFO - Error in mapping city tiers: unable to open database file
[2025-02-22 11:33:20,368] {python.py:173} INFO - Done. Returned value was: None
[2025-02-22 11:33:20,373] {taskinstance.py:1415} INFO - Marking task as SUCCESS. dag_id=lead_scoring_data_pipeline, task_id=map_city_tier, execution_date=20241006T000000, start_date=20250222T113320, end_date=20250222T113320
[2025-02-22 11:33:20,427] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-02-22 11:33:20,466] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
